#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WWP.Droid.Resource", IsApplication=true)]

namespace WWP.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int apple = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int back = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int backButton = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int backgroundBlob = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int badge = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int beverages = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int beveragesFilled = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int beveragesUnfilled = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int browseButton = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int cannedFoods = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int cannedFoodsFilled = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int cannedFoodsUnfilled = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int clock = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int continueButton = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int dairy = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int dairyFilled = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int dairyUnfilled = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int dateSelected = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int dateUnselected = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int desserts = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int dessertsFilled = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int dessertsUnfilled = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int editProfileButton = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int emptyCircle = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int enterButton = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int eye = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int facebook = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int fruits = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int fruitsFilled = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int fruitsUnfilled = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int WWPIconCustomize = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int google = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int highFive = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int home = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int loginButton = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int mapsButton = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int meals = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int mealsFilled = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int mealsUnfilled = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int menu = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int menuFAQ = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int menuGrid = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int menuLogin = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int menuLogout = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public const int menuProfile = 2130837548;
			
			// aapt resource value: 0x7F02002D
			public const int menuSearch = 2130837549;
			
			// aapt resource value: 0x7F02002E
			public const int menuUtensils = 2130837550;
			
			// aapt resource value: 0x7F02002F
			public const int openedMenu = 2130837551;
			
			// aapt resource value: 0x7F020030
			public const int phone = 2130837552;
			
			// aapt resource value: 0x7F020031
			public const int profileCircle = 2130837553;
			
			// aapt resource value: 0x7F020032
			public const int registerButton = 2130837554;
			
			// aapt resource value: 0x7F020033
			public const int rightArrow = 2130837555;
			
			// aapt resource value: 0x7F020034
			public const int shopping = 2130837556;
			
			// aapt resource value: 0x7F020035
			public const int snacks = 2130837557;
			
			// aapt resource value: 0x7F020036
			public const int snacksFilled = 2130837558;
			
			// aapt resource value: 0x7F020037
			public const int snacksUnfilled = 2130837559;
			
			// aapt resource value: 0x7F020038
			public const int startOrderButton = 2130837560;
			
			// aapt resource value: 0x7F020039
			public const int tallOval = 2130837561;
			
			// aapt resource value: 0x7F02003A
			public const int vegetables = 2130837562;
			
			// aapt resource value: 0x7F02003B
			public const int vegetablesFilled = 2130837563;
			
			// aapt resource value: 0x7F02003C
			public const int vegetablesUnfilled = 2130837564;
			
			// aapt resource value: 0x7F02003D
			public const int work = 2130837565;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int sliding_tabs = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int toolbar = 2130903041;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Tabbar = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Toolbar = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int WWPIcon = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int icon = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int icon_round = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int launcher_foreground = 2131034115;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7F060000
			public const int pulseLoadingAnim = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int pulseLoadingAnim2 = 2131099649;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int MainTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
